export type Folder = {
  id: string;
  name: string;
  companyId?: string | null;
  company?: string | null;
  statusColumn?: 'entrada' | 'andamento' | 'concluido';
  position?: number | null;
  hourRate?: number | null;
  hourRate50?: number | null;
  hourRate100?: number | null;
  normalHoursPerDay?: number | null;
  signatures?: Array<{ name: string; role: string }> | null;
  foCode?: string | null;
  foEmission?: string | null;
  foRevision?: string | null;
  foNumber?: string | number | null;
  linkKeyHash: string;
  createdAt: number;
  updatedAt: number;
};
